name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # GitHub Actions 환경 설정
      - name: Checkout code
        uses: actions/checkout@v3

      # SSH 키 추가
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Node.js 설치
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # PM2 배포 실행
      - name: Deploy with PM2
        run: |
          npm install pm2 -g
          pm2 deploy ecosystem.config.js production


      - name: Debug SSH Connection
        run: ssh -v ubuntu@13.209.156.54 echo "SSH connection successful"