name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. SSH 에이전트 설정
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3. 서버 호스트 키 등록
      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H 13.209.156.54 >> ~/.ssh/known_hosts

      # 4. SSH 연결 디버깅
      - name: Debug SSH Connection
        run: ssh -v ubuntu@13.209.156.54 echo "SSH connection successful"

      # 5. Node.js 환경 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 6. PM2 배포 실행
      - name: Deploy with PM2
        run: |
          npm install pm2 -g
          pm2 deploy ecosystem.config.js production